// Generated by CoffeeScript 1.10.0
(function() {
  'use strict';
  var Config, Sync, _, config, configPath, dryrun, force_tail, loglv, opts, sync;

  opts = require('opts');

  _ = require('underscore');

  opts.parse([
    {
      short: 'c',
      long: 'config',
      description: 'configPath',
      value: true,
      required: true
    }, {
      short: 'f',
      long: 'force-tail',
      description: 'Sync from tail of the OpLog. (Ignoring last sync TS)',
      value: false,
      required: false
    }, {
      short: 't',
      long: 'dry-run',
      description: 'dry run mode',
      value: false,
      required: false
    }, {
      short: 'l',
      long: 'loglv',
      description: 'debug/verbose/info/error',
      value: true,
      required: false
    }
  ]);

  configPath = opts.get('config');

  force_tail = opts.get('force-tail');

  dryrun = opts.get('dry-run');

  loglv = opts.get('loglv');

  Sync = require('./sync');

  Config = require('./config');

  config = Config.load(configPath);

  if (!_.isUndefined(force_tail)) {
    config.options.force_tail = force_tail;
  }

  if (!_.isUndefined(dryrun)) {
    config.options.dryrun = dryrun;
  }

  if (!_.isUndefined(loglv)) {
    config.options.loglv = loglv;
  }

  sync = new Sync(config);

  sync.start(function(err) {
    if (err) {
      console.log(err);
      process.exit(1);
    }
    return process.exit(0);
  });

}).call(this);
