// Generated by CoffeeScript 1.10.0
(function() {
  var fs;

  fs = require('fs');

  exports.load = function(file_path) {
    var body, obj;
    body = fs.readFileSync(file_path).toString();
    obj = eval("obj = " + body);
    return obj;
  };

}).call(this);
